### ISSUE TITLE
Dotty effect system

### ISSUE THREAD

**Issue by siriux** [TiarkRompf/scala-escape#2]
Hi, 

this plugin is really interesting, and it solves many things I've been trying to do for a long time. 

But I wonder if you have talked with the dotty team about it, because they are thinking about implementing an effect system based on implicits (with capabilities to produce effects).

As the functionality of both things overlaps in some areas, do you think your idea could be used in the dotty effect system to get the best of both?

Just to be clear, I have no idea about the implementation details of the effect system, I just know what Martin Odersky explains in his presentations.

**Comment by TiarkRompf** [comment]
Thanks! Sure, the Dotty team is aware of this, and I believe they will end up with something similar once their design is more fleshed out.
