### ISSUE TITLE
@safe and EscAnnotationChecker.scala

### ISSUE THREAD

**Issue by freddie-freeloader** [TiarkRompf/scala-escape#3]
Hi! :smiley: 

I have read the paper related to this repository and experimented a bit with the compiler plugin.

One thing I have not fully understood is the role of the `EscAnnotationChecker.scala` phase. What kind of properties does this phase try to ensure?

**Comment by TiarkRompf** [comment]
The annotation checker is from a previous version and no longer used.

**Comment by freddie-freeloader** [comment]
Thank you for the quick reply!
